/* Auto-generated by scan_place_photos.py — do not edit by hand */
window.PLACE_PHOTO_MANIFEST = {
  "d1": [
    "place-photos/day-01/d1/ahmedabad-junction.webp",
    "place-photos/day-01/d1/ahmedabad-railways-station.webp"
  ]
};
