/* Auto-generated by scan_place_photos.py — do not edit by hand */
window.PLACE_PHOTO_MANIFEST = {
  "d1": [
    "place-photos/day-01/d1/ahmedabad-junction.webp",
    "place-photos/day-01/d1/ahmedabad-railways-station.webp"
  ],
  "d2a": [
    "place-photos/day-02/d2a/Chandigarh_junction.jpg"
  ],
  "d2b": [
    "place-photos/day-02/d2b/Buses-from-Shimla-Lakkar-Bazar-Bus-Stand.jpg",
    "place-photos/day-02/d2b/ISBT_Shimla.jpg",
    "place-photos/day-02/d2b/Landscape_of_Shimla_,_Himachal_Pradesh.jpg",
    "place-photos/day-02/d2b/isbt-shimla-new-bus-stand-manali-1.webp",
    "place-photos/day-02/d2b/the-ridge.jpg"
  ]
};
