/* Auto-generated by scan_place_photos.py — do not edit by hand */
window.PLACE_PHOTO_MANIFEST = {
  "d1": [
    "place-photos/day-01/d1/ahmedabad-junction.webp",
    "place-photos/day-01/d1/ahmedabad-railways-station.webp"
  ],
  "d2a": [
    "place-photos/day-02/d2a/Chandigarh_junction.jpg"
  ],
  "d2b": [
    "place-photos/day-02/d2b/Buses-from-Shimla-Lakkar-Bazar-Bus-Stand.jpg",
    "place-photos/day-02/d2b/ISBT_Shimla.jpg",
    "place-photos/day-02/d2b/Landscape_of_Shimla_,_Himachal_Pradesh.jpg",
    "place-photos/day-02/d2b/isbt-shimla-new-bus-stand-manali-1.webp",
    "place-photos/day-02/d2b/the-ridge.jpg"
  ],
  "d3a": [
    "place-photos/day-03/d3a/531957231Jakhu_Temple_Main.jpg",
    "place-photos/day-03/d3a/Hanuman Statue Pinterest--46691a.jpg",
    "place-photos/day-03/d3a/Shimla_Jakhu_Temple_1622447113819.jpg",
    "place-photos/day-03/d3a/jakhoo-temple-is-an-ancient-temple-in-shimla-dedicated-to-v0-a0ww2dmouky01.webp",
    "place-photos/day-03/d3a/jakhu-temple.jpg",
    "place-photos/day-03/d3a/kufri-jakhoo-temple.jpg.imgw.1280.1280.jpeg",
    "place-photos/day-03/d3a/shimla-hills-and-jakhu.jpg"
  ],
  "d3b": [
    "place-photos/day-03/d3b/183128172_80e060c6cf_b.jpg",
    "place-photos/day-03/d3b/National_Highway_22_-_Kufri_2014-05-08_1714.JPG",
    "place-photos/day-03/d3b/caption.jpg",
    "place-photos/day-03/d3b/deal_iimage22735-1.jpg",
    "place-photos/day-03/d3b/himachal-1.jpg",
    "place-photos/day-03/d3b/how-reach-kufri.jpg",
    "place-photos/day-03/d3b/shimla-to-kufri-distance.webp",
    "place-photos/day-03/d3b/the-kurfi-mountains.jpg"
  ],
  "d3c": [
    "place-photos/day-03/d3c/296097681Narkanda_Skiing_Point_Main.jpg",
    "place-photos/day-03/d3c/29609797Hatu.jpg",
    "place-photos/day-03/d3c/3025753c3a7c75a810c94ddba20dd9db.jpg",
    "place-photos/day-03/d3c/9085ac_4344798f237e478eb31fddbbb7791568~mv2.jpg",
    "place-photos/day-03/d3c/Narkanda.jpg",
    "place-photos/day-03/d3c/chandigarh-shimla-narkanda-chandigarh-3-night-4-days-taxi-tour-package.webp",
    "place-photos/day-03/d3c/narkanda.jpg"
  ]
};
